name: Mutation tests (full)

on:
  push:
    branches:
      - main

jobs:
  cargo-mutants:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          fetch-depth: 0

      - name: Install rust
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1

      - name: Install cargo-mutants
        uses: taiki-e/install-action@44c6d64aa62cd779e873306675c7a58e86d6d532
        with:
          tool: cargo-mutants

      - name: Run mutant tests
        run: cargo mutants -vV --no-shuffle --in-place

      - name: Archive mutants.out
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
        if: always()
        with:
          name: mutants-full.out
          path: mutants.out
