name: Mutation tests (incremental, for PRs)

on:
  pull_request:
    branches:
      - main
    paths:
      - ".cargo/**"
      - ".github/workflows/mutants.yml"
      - "Cargo.*"
      - "src/**"

jobs:
  cargo-mutants:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0

      - name: Relative diff
        run: |
          git branch -av
          git diff origin/${{ github.base_ref }}.. | tee git.diff

      - name: Install rust
        uses: dtolnay/rust-toolchain@b3b07ba8b418998c39fb20f53e8b695cdcc8de1b
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0

      - name: Install cargo-mutants
        uses: taiki-e/install-action@f63c33fd96cc1e69a29bafd06541cf28588b43a4
        with:
          tool: cargo-mutants

      - name: Run mutant tests
        run: cargo mutants -vV --no-shuffle --in-place --in-diff git.diff

      - name: Archive mutants.out
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        if: always()
        with:
          name: mutants-incremental.out
          path: mutants.out
