name: Mutation tests (full)

on:
  push:
    branches:
      - main

jobs:
  cargo-mutants:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
        with:
          fetch-depth: 0

      - name: Install rust
        uses: dtolnay/rust-toolchain@b3b07ba8b418998c39fb20f53e8b695cdcc8de1b
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0

      - name: Install cargo-mutants
        uses: taiki-e/install-action@6064345e6658255e90e9500fdf9a06ab77e6909c
        with:
          tool: cargo-mutants

      - name: Run mutant tests
        run: cargo mutants -vV --no-shuffle --in-place

      - name: Archive mutants.out
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        if: always()
        with:
          name: mutants-full.out
          path: mutants.out
