name: Mutation tests (incremental, for PRs)

on:
  pull_request:
    branches:
      - main
    paths:
      - ".cargo/**"
      - ".github/workflows/mutants.yml"
      - "Cargo.*"
      - "src/**"

jobs:
  cargo-mutants:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 0

      - name: Relative diff
        run: |
          git branch -av
          git diff origin/${{ github.base_ref }}.. | tee git.diff

      - name: Install rust
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1

      - name: Install cargo-mutants
        uses: taiki-e/install-action@81ee1d48d9194cdcab880cbdc7d36e87d39874cb
        with:
          tool: cargo-mutants

      - name: Run mutant tests
        run: cargo mutants -vV --no-shuffle --in-place --in-diff git.diff

      - name: Archive mutants.out
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        if: always()
        with:
          name: mutants-incremental.out
          path: mutants.out
